version: "3.9"
services:
  email-services:
    build: 
      context: ./
    ports:
      - "4000:4000"
    networks:
      - email-server-net
  nginx:
    build: 
      context: ./nginx
    ports: 
      - "80:80"
    depends_on:
      - email-service
    networks:
      - email-server-net

networks:
  email-server-net:
    external: true