version: "3.3"
services:
  email-service:
    build: 
      context: ./
    command: npm start
    ports:
      - 4000:4000
  nginx-service:
    build: 
      context: ./nginx
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
